"""empty message

Revision ID: f96ccdd36974
Revises: dcd782df6e70
Create Date: 2025-10-10 13:41:50.632791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f96ccdd36974"
down_revision: Union[str, Sequence[str], None] = "dcd782df6e70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("vk_id", sa.String(), nullable=True))
    op.create_unique_constraint(op.f("uq_users_vk_id"), "users", ["vk_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_vk_id"), "users", type_="unique")
    op.drop_column("users", "vk_id")
    # ### end Alembic commands ###
