"""empty message

Revision ID: ccb104f7fbbd
Revises: 36c43176cbe2
Create Date: 2025-10-07 13:55:38.315252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccb104f7fbbd"
down_revision: Union[str, Sequence[str], None] = "36c43176cbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
