"""empty message

Revision ID: 51807b8f22f5
Revises: a4ab5c133b21
Create Date: 2025-10-08 19:09:58.434664

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51807b8f22f5"
down_revision: Union[str, Sequence[str], None] = "a4ab5c133b21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("user_owner", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_scores_user_owner_users"),
        "scores",
        "users",
        ["user_owner"],
        ["id"],
    )
    op.drop_constraint(op.f("users_telegram_id_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_telegram_id"), "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_telegram_id"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_telegram_id_key"),
        "users",
        ["telegram_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("fk_scores_user_owner_users"), "scores", type_="foreignkey")
    op.drop_column("scores", "user_owner")
    # ### end Alembic commands ###
