"""empty message

Revision ID: a844093a7679
Revises: ccb104f7fbbd
Create Date: 2025-10-07 14:52:14.001955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a844093a7679"
down_revision: Union[str, Sequence[str], None] = "ccb104f7fbbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "telegram_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.create_unique_constraint(None, "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True
    )
    op.alter_column(
        "users", "telegram_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
